# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      # Replace this with a real test runner invocation
      - run:
          name: say hello
          command: echo "Say hello to YAML!"
  say_goodbye:
    docker:
      - image: cimg/base:2022.05
    steps:
      # Replace this with steps to build a package, or executable
      - run:
          name: say goodbye
          command: echo "Say goodbye to YAML!"
workflows:
  hello_and_goodbye:
    jobs:
       - say_hello
      - say_goodbye
